// <auto-generated />
using System;
using KuemSoft.FullBlogApp.Repository.Contexts.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KuemSoft.FullBlogApp.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250117213149_SeedDataAddedAndİnitialDb")]
    partial class SeedDataAddedAndİnitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<Guid>("ArticlesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArticlesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ArticleTag");
                });

            modelBuilder.Entity("KuemSoft.FullBlogApp.Core.Entities.Concrete.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7143e119-7e8f-4205-abb2-41434d76f197"),
                            Name = "superadmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = new Guid("76a068b9-09d7-42f5-b374-d54b18c51506"),
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("c4d92192-8316-45cd-84dc-e81dc5b80b8b"),
                            Name = "member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("KuemSoft.FullBlogApp.Core.Entities.Concrete.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa8504d6-2b32-4e89-8ec0-2f4ebe57074b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d079b79-5fc0-4896-ba61-27029777851a",
                            Email = "superadmin@kuemsoft.com",
                            EmailConfirmed = true,
                            FirstName = "Arif",
                            LastName = "ORAK",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@KUEMSOFT.COM",
                            NormalizedUserName = "SUPERADMIN@KUEMSOFT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKS+pEKKpzqOgyv2tsRp5QdkY1z/uuXvjZc3wPi78tjoF9x7l13LLGeKRvB/XUcr1w==",
                            PhoneNumber = "0111 222 33 44",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c37c5f25-9f2c-4bfb-897d-d81e313ae291",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@kuemsoft.com"
                        },
                        new
                        {
                            Id = new Guid("f19cc326-05f2-4305-ad39-f4e0645aeca0"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8c5a968b-6710-4ff5-82c9-1c1cb717d5c3",
                            Email = "member@kuemsoft.com",
                            EmailConfirmed = true,
                            FirstName = "Alparslan",
                            LastName = "ORAK",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER@KUEMSOFT.COM",
                            NormalizedUserName = "MEMBER@KUEMSOFT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFiVw2Zx+Zn2jFYNU0+D7GGqEXvKGi6FpydITh2o/cMR9Qxll+7iaZqSpuUfFz0XOg==",
                            PhoneNumber = "0111 222 33 44",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d81e1124-12b5-4424-8113-6e66b8291a35",
                            TwoFactorEnabled = false,
                            UserName = "member@kuemsoft.com"
                        });
                });

            modelBuilder.Entity("KuemSoft.FullBlogApp.Core.Entities.Concrete.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40b63cd3-d9d4-4e47-906f-ea4564b4d827"),
                            AppUserId = new Guid("aa8504d6-2b32-4e89-8ec0-2f4ebe57074b"),
                            Content = "ASP.Net Core Teknolojisi İle Web backend GeliştirmekASP.Net Core Teknolojisi İle Web backend GeliştirmekASP.Net Core Teknolojisi İle Web backend GeliştirmekASP.Net Core Teknolojisi İle Web backend GeliştirmekASP.Net Core Teknolojisi İle Web backend GeliştirmekASP.Net Core Teknolojisi İle Web backend Geliştirmek",
                            CreatedBy = "Adminastrator",
                            CreatedDate = new DateTime(2025, 1, 18, 0, 31, 49, 42, DateTimeKind.Local).AddTicks(3017),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = "Adminastrator",
                            ModifiedDate = new DateTime(2025, 1, 18, 0, 31, 49, 42, DateTimeKind.Local).AddTicks(3018),
                            Title = "ASP.Net Core Teknolojisi İle Web backend Geliştirmek"
                        },
                        new
                        {
                            Id = new Guid("c1b57612-0f59-4d8d-956e-07e40fc7734a"),
                            AppUserId = new Guid("aa8504d6-2b32-4e89-8ec0-2f4ebe57074b"),
                            Content = "ANodeJs ile Restfull Web API GeliştirmekNodeJs ile Restfull Web API GeliştirmekNodeJs ile Restfull Web API GeliştirmekNodeJs ile Restfull Web API GeliştirmekNodeJs ile Restfull Web API GeliştirmekNodeJs ile Restfull Web API GeliştirmekNodeJs ile Restfull Web API GeliştirmekNodeJs ile Restfull Web API GeliştirmekNodeJs ile Restfull Web API GeliştirmekNodeJs ile Restfull Web API Geliştirmek",
                            CreatedBy = "Adminastrator",
                            CreatedDate = new DateTime(2025, 1, 18, 0, 31, 49, 42, DateTimeKind.Local).AddTicks(3021),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = "Adminastrator",
                            ModifiedDate = new DateTime(2025, 1, 18, 0, 31, 49, 42, DateTimeKind.Local).AddTicks(3022),
                            Title = "NodeJs ile Restfull Web API Geliştirmek"
                        });
                });

            modelBuilder.Entity("KuemSoft.FullBlogApp.Core.Entities.Concrete.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("KuemSoft.FullBlogApp.Core.Entities.Concrete.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9679a96b-e6e6-44a5-b04e-20c80d70bd4b"),
                            CreatedBy = "Adminastrator",
                            CreatedDate = new DateTime(2025, 1, 18, 0, 31, 49, 42, DateTimeKind.Local).AddTicks(3640),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = "Admiastrator",
                            ModifiedDate = new DateTime(2025, 1, 18, 0, 31, 49, 42, DateTimeKind.Local).AddTicks(3640),
                            Text = "Web Programlama"
                        },
                        new
                        {
                            Id = new Guid("8183e35a-277b-4c1f-8a66-d75f68b80bf5"),
                            CreatedBy = "Adminastrator",
                            CreatedDate = new DateTime(2025, 1, 18, 0, 31, 49, 42, DateTimeKind.Local).AddTicks(3642),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = "Admiastrator",
                            ModifiedDate = new DateTime(2025, 1, 18, 0, 31, 49, 42, DateTimeKind.Local).AddTicks(3643),
                            Text = "Mobil Programlama"
                        },
                        new
                        {
                            Id = new Guid("10b0d58b-8155-48f7-a334-977513ec67d0"),
                            CreatedBy = "Adminastrator",
                            CreatedDate = new DateTime(2025, 1, 18, 0, 31, 49, 42, DateTimeKind.Local).AddTicks(3645),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = "Admiastrator",
                            ModifiedDate = new DateTime(2025, 1, 18, 0, 31, 49, 42, DateTimeKind.Local).AddTicks(3646),
                            Text = "Masaüstü Programlama"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("KuemSoft.FullBlogApp.Core.Entities.Concrete.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuemSoft.FullBlogApp.Core.Entities.Concrete.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuemSoft.FullBlogApp.Core.Entities.Concrete.Article", b =>
                {
                    b.HasOne("KuemSoft.FullBlogApp.Core.Entities.Concrete.AppUser", "AppUser")
                        .WithMany("Articles")
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("KuemSoft.FullBlogApp.Core.Entities.Concrete.Comment", b =>
                {
                    b.HasOne("KuemSoft.FullBlogApp.Core.Entities.Concrete.AppUser", "AppUser")
                        .WithMany("Comments")
                        .HasForeignKey("AppUserId");

                    b.HasOne("KuemSoft.FullBlogApp.Core.Entities.Concrete.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.Navigation("AppUser");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("KuemSoft.FullBlogApp.Core.Entities.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KuemSoft.FullBlogApp.Core.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KuemSoft.FullBlogApp.Core.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("KuemSoft.FullBlogApp.Core.Entities.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuemSoft.FullBlogApp.Core.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KuemSoft.FullBlogApp.Core.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuemSoft.FullBlogApp.Core.Entities.Concrete.AppUser", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
